### ISSUE TITLE
TypeError: SparseDataFrame() take no arguments

### ISSUE THREAD

**Issue by yquserg** [lozuponelab/SCNIC#17]
When i run：SCNIC_analysis.py within, "TypeError: SparseDataFrame() takes no arguments" occur.

**Comment by yquserg** [comment]
(SCNIC) scnic@scnic-VirtualBox:~$ SCNIC_analysis.py within -i Scnic/feature-table.biom -o Scnic/ -m sparcc --verbose
Table loaded: 2100 observations

/home/scnic/miniconda2/envs/SCNIC/lib/python3.8/site-packages/biom/table.py:4064: FutureWarning: The SparseDataFrame class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  constructor = partial(pd.SparseDataFrame,
Traceback (most recent call last):
  File "/home/scnic/miniconda2/envs/SCNIC/bin/SCNIC_analysis.py", line 81, in <module>
    main()
  File "/home/scnic/miniconda2/envs/SCNIC/bin/SCNIC_analysis.py", line 77, in main
    args.func(**args_dict)
  File "/home/scnic/miniconda2/envs/SCNIC/lib/python3.8/site-packages/SCNIC/within_correls.py", line 68, in within_correls
    correls = ca.fastspar_correlation(table_filt, verbose=verbose, nprocs=procs)
  File "/home/scnic/miniconda2/envs/SCNIC/lib/python3.8/site-packages/SCNIC/correlation_analysis.py", line 77, in fastspar_correlation
    table.to_dataframe().to_dense().to_csv(path.join(temp, 'otu_table.tsv'), sep='\t', index_label='#OTU ID')
  File "/home/scnic/miniconda2/envs/SCNIC/lib/python3.8/site-packages/biom/table.py", line 4068, in to_dataframe
    return constructor(mat, index=index, columns=columns)
TypeError: SparseDataFrame() takes no arguments

I am wondering if there is a way to solve this.

**Comment by yquserg** [comment]
When I changed the version of pandas, I got the following message:
Correls.txt written
Traceback (most recent call last):
  File "/home/scnic/miniconda2/envs/SCNIC5/bin/SCNIC_analysis.py", line 81, in <module>
    main()
  File "/home/scnic/miniconda2/envs/SCNIC5/bin/SCNIC_analysis.py", line 77, in main
    args.func(**args_dict)
  File "/home/scnic/miniconda2/envs/SCNIC5/lib/python3.6/site-packages/SCNIC/within_correls.py", line 85, in within_correls
    net = general.correls_to_net(correls, metadata=metadata)
  File "/home/scnic/miniconda2/envs/SCNIC5/lib/python3.6/site-packages/SCNIC/general.py", line 97, in correls_to_net
    if otu not in graph.node:
AttributeError: 'Graph' object has no attribute 'node'

**Comment by afvrbanac** [comment]
Also getting this same error. This is what I did (all in a conda env):

pip install --user pandas==0.25.3
Error: scikit-bio 0.5.6 requires pandas>=1.0.0, but you'll have pandas 0.25.3 which is incompatible.

pip install --user scikit-bio==0.5.5

I got this error when I try to use SCNIC:
FileNotFoundError: [Errno 2] No such file or directory: 'fastspar'

conda install -c bioconda -c conda-forge fastspar

It's working for me after doing this

**Comment by vanesotjim** [comment]
Hi,
I am running SCNIC but couldn't install the plugin in qiime2, for this reason, I am running independently, but I got the same error, what I can do?
Please if anybody have an idea, it would be very nice.
Thanks in advance

SCNIC_analysis.py within -i table_filt_2_20Q_w_tax__VSEARCH_oref_dnvo_NM_NC.biom -o within_output/ -m sparcc
/vault2/soft/miniconda2/envs/SCNIC/lib/python3.8/site-packages/biom/table.py:4064: FutureWarning: The SparseDataFrame class is removed from pandas. Accessing it from the top-level pace will also be removed in the next version
  constructor = partial(pd.SparseDataFrame,
Traceback (most recent call last):
  File "/vault2/soft/miniconda2/envs/SCNIC/bin/SCNIC_analysis.py", line 81, in <module>
    main()
  File "/vault2/soft/miniconda2/envs/SCNIC/bin/SCNIC_analysis.py", line 77, in main
    args.func(**args_dict)
  File "/vault2/soft/miniconda2/envs/SCNIC/lib/python3.8/site-packages/SCNIC/within_correls.py", line 68, in within_correls
    correls = ca.fastspar_correlation(table_filt, verbose=verbose, nprocs=procs)
  File "/vault2/soft/miniconda2/envs/SCNIC/lib/python3.8/site-packages/SCNIC/correlation_analysis.py", line 77, in fastspar_correlation
    table.to_dataframe().to_dense().to_csv(path.join(temp, 'otu_table.tsv'), sep='\t', index_label='#OTU ID')
  File "/vault2/soft/miniconda2/envs/SCNIC/lib/python3.8/site-packages/biom/table.py", line 4068, in to_dataframe
    return constructor(mat, index=index, columns=columns)
TypeError: SparseDataFrame() takes no arguments

**Comment by marcjermaine-pontiveros** [comment]
Hello everyone! I've encountered the same error. I've made a pull request hoping to resolve the same issue. https://github.com/shafferm/SCNIC/pull/21/commits/c5b76d8c940a65e86bce2d2aa8996c4b39bb0457

**Comment by sterrettJD** [comment]
Issue has been fixed in latest version of SCNIC (0.6.3).
